### ISSUE TITLE
Not working with Sketch V53.2

### ISSUE THREAD

**Issue by MaxHasADHD** [MengTo/Angle-Sketch-Plugin#46]
I'm seeing this error in the console ```TypeError: this.targetLayer.points is not a function. (In 'this.targetLayer.points()', 'this.targetLayer.points' is undefined)``` when I use a angled device mock up.

**Comment by MaxHasADHD** [comment]
It also flips the image when it does work, so it's backwards... It only works with iPhone X - 01, but not 02 - right
